rot:
	g++ rotate_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL

trans:
	g++ translation_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL

2rot:
	g++ rotate2_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL

snowman:
	g++ snow_man.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL

pinta_model:
	g++ pinta_model.cpp model.o -o pinta_model.exe -I /assig/idi/include/ /usr/lib/libglut.so.3 /usr/lib/libGL.so.1 /usr/lib/libGLU.so.1 -lGL

solar:
	g++ solar_system.cpp model.o -o solar_system.exe -I /assig/idi/include/ /usr/lib/libglut.so.3 /usr/lib/libGL.so.1 /usr/lib/libGLU.so.1 -lGL

clean:
	rm -f *.exe *.out *~$ 
