rot:
	g++ rotate_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL
trans:
	g++ translation_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL
2rot:
	g++ rotate2_figures.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL
snowman:
	g++ snow_man.cpp -I /assig/idi/include/ /usr/lib/libglut.so.3 -lGL

clean:
	rm -f *.o *.out *~$ 


